services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - ~/.mytb-data:/data
      - ~/.mytb-logs:/var/log/thingsboard
      - .:/app
  

  fastapi-app:   
    build:
      context: . 
      dockerfile: Dockerfile 
    ports:
      - "8060:8060" 
    volumes:
      - .:/app
    env_file:
      - .env
      
  mysql:
    restart: always
    image: mysql:latest
    container_name: mysql
    ports:
        - "3306:3306"
    env_file:
        - .env
    environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
        - mysql_data:/var/lib/mysql 
        - ./sql_scripts:/docker-entrypoint-initdb.d
    healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

 
  mlflow:
      restart: always
      build: 
          context: ./mlflow
          dockerfile: Dockerfile
      container_name: mlflow_server
      ports:
          - "5000:5000"
      env_file:
          - .env
      environment:
          - MYSQL_HOST=mysql
          - MYSQL_PORT=3306
          - MYSQL_USER=${MYSQL_USER}
          - MYSQL_PASSWORD=${MYSQL_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE}
          - S3_MLFLOW_BUCKET=${S3_MLFLOW_BUCKET}
          - MLFLOW_S3_ENDPOINT_URL=${S3_ENDPOINT_URL}
          - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
          - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      depends_on:
          mysql:
              condition: service_healthy
      volumes:
          - mlflow-data:/mlflow



  mageai:
    image: mageai/mageai:latest
    container_name: mage_ai_server
    ports:
      - "6789:6789"
    environment:
      - MAGE_ENV=production
    volumes:
      - mage-data:/home/mage-ai



volumes:
  mytb-data:
  mytb-logs:
  mysql_data:
  mlflow-data:
  mage-data:
